import type { Locale } from "@/i18n/utils/config";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getDictionary } from "@/i18n/utils/getDictionary";
import TranslationProvider from "@/i18n/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function Root({
    children,
    params,
}: {
    children: React.ReactNode;
    params: { lang: Locale };
}) {
    const dictionary = await getDictionary(params.lang);
    return (
        <TranslationProvider dictionary={dictionary}>
            <html lang={params.lang}>
                <body className={inter.className}>{children}</body>
            </html>
        </TranslationProvider>
    );
}
